/********************************************************************************
** Form generated from reading UI file 'dummy.ui'
**
** Created by: Qt User Interface Compiler version 5.1.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DUMMY_H
#define UI_DUMMY_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Dummy
{
public:
    QAction *actionOpen;
    QAction *actionSave;
    QAction *actionDelete;
    QAction *actionUndo;
    QAction *actionAuthor;
    QAction *actionTool;
    QAction *actionNew;
    QAction *actionOpen_2;
    QWidget *centralWidget;
    QRadioButton *radioButton;
    QRadioButton *radioButton_2;
    QLabel *label;
    QGroupBox *groupBox;
    QWidget *layoutWidget;
    QHBoxLayout *horizontalLayout;
    QLabel *label_2;
    QComboBox *comboBox;
    QLabel *label_3;
    QComboBox *comboBox_2;
    QGroupBox *groupBox_2;
    QWidget *widget;
    QHBoxLayout *horizontalLayout_2;
    QRadioButton *radioButton_3;
    QRadioButton *radioButton_4;
    QLabel *label_4;
    QSpinBox *spinBox;
    QGroupBox *groupBox_3;
    QGroupBox *groupBox_4;
    QLabel *label_5;
    QLineEdit *lineEdit;
    QPushButton *pushButton;
    QPushButton *pushButton_4;
    QLabel *label_8;
    QLineEdit *lineEdit_4;
    QPushButton *pushButton_5;
    QLineEdit *lineEdit_5;
    QLabel *label_9;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QLineEdit *lineEdit_6;
    QLabel *label_10;
    QLineEdit *lineEdit_7;
    QLabel *label_11;
    QLabel *label_12;
    QLineEdit *lineEdit_8;
    QLabel *label_13;
    QPushButton *pushButton_9;
    QLineEdit *lineEdit_9;
    QLineEdit *lineEdit_17;
    QLabel *label_21;
    QPushButton *pushButton_17;
    QLineEdit *lineEdit_18;
    QLabel *label_22;
    QPushButton *pushButton_18;
    QLineEdit *lineEdit_19;
    QLabel *label_23;
    QPushButton *pushButton_19;
    QGroupBox *groupBox_5;
    QLabel *label_6;
    QLineEdit *lineEdit_2;
    QPushButton *pushButton_2;
    QPushButton *pushButton_40;
    QLabel *label_44;
    QLineEdit *lineEdit_40;
    QPushButton *pushButton_41;
    QLineEdit *lineEdit_41;
    QLabel *label_45;
    QPushButton *pushButton_42;
    QPushButton *pushButton_43;
    QPushButton *pushButton_44;
    QLineEdit *lineEdit_42;
    QLabel *label_46;
    QLineEdit *lineEdit_43;
    QLabel *label_47;
    QLabel *label_48;
    QLineEdit *lineEdit_44;
    QLabel *label_49;
    QPushButton *pushButton_45;
    QLineEdit *lineEdit_45;
    QLineEdit *lineEdit_46;
    QLabel *label_50;
    QPushButton *pushButton_46;
    QLineEdit *lineEdit_47;
    QLabel *label_51;
    QPushButton *pushButton_47;
    QLineEdit *lineEdit_48;
    QLabel *label_52;
    QPushButton *pushButton_48;
    QPushButton *Load;
    QPushButton *RunModel;
    QPushButton *Close;
    QCheckBox *checkBox;
    QCheckBox *checkBox_2;
    QLabel *pb_logo;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QMenu *menuEdit;
    QMenu *menuAbout;

    void setupUi(QMainWindow *Dummy)
    {
        if (Dummy->objectName().isEmpty())
            Dummy->setObjectName(QStringLiteral("Dummy"));
        Dummy->resize(849, 495);
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(229, 255, 199, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(255, 255, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(242, 255, 227, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(114, 127, 99, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(153, 170, 133, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        QBrush brush6(QColor(255, 255, 220, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        Dummy->setPalette(palette);
        Dummy->setMouseTracking(false);
        Dummy->setWindowOpacity(1);
        actionOpen = new QAction(Dummy);
        actionOpen->setObjectName(QStringLiteral("actionOpen"));
        actionOpen->setCheckable(true);
        QIcon icon;
        icon.addFile(QStringLiteral("Resource/3pics.BMP"), QSize(), QIcon::Normal, QIcon::On);
        actionOpen->setIcon(icon);
        actionSave = new QAction(Dummy);
        actionSave->setObjectName(QStringLiteral("actionSave"));
        QIcon icon1;
        icon1.addFile(QStringLiteral("Resource/4pics.BMP"), QSize(), QIcon::Normal, QIcon::On);
        actionSave->setIcon(icon1);
        actionDelete = new QAction(Dummy);
        actionDelete->setObjectName(QStringLiteral("actionDelete"));
        actionUndo = new QAction(Dummy);
        actionUndo->setObjectName(QStringLiteral("actionUndo"));
        actionAuthor = new QAction(Dummy);
        actionAuthor->setObjectName(QStringLiteral("actionAuthor"));
        actionTool = new QAction(Dummy);
        actionTool->setObjectName(QStringLiteral("actionTool"));
        actionNew = new QAction(Dummy);
        actionNew->setObjectName(QStringLiteral("actionNew"));
        actionOpen_2 = new QAction(Dummy);
        actionOpen_2->setObjectName(QStringLiteral("actionOpen_2"));
        centralWidget = new QWidget(Dummy);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        radioButton = new QRadioButton(centralWidget);
        radioButton->setObjectName(QStringLiteral("radioButton"));
        radioButton->setGeometry(QRect(160, 20, 121, 17));
        radioButton_2 = new QRadioButton(centralWidget);
        radioButton_2->setObjectName(QStringLiteral("radioButton_2"));
        radioButton_2->setGeometry(QRect(280, 20, 66, 17));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(30, 20, 121, 18));
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(20, 50, 351, 41));
        QPalette palette1;
        QBrush brush7(QColor(0, 0, 127, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush7);
        QBrush brush8(QColor(0, 0, 255, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush8);
        QBrush brush9(QColor(127, 127, 255, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush9);
        QBrush brush10(QColor(63, 63, 255, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush10);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush7);
        QBrush brush11(QColor(0, 0, 170, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush11);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush7);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush7);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush9);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        QBrush brush12(QColor(176, 176, 176, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush12);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        QBrush brush13(QColor(135, 150, 154, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush13);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        QBrush brush14(QColor(141, 141, 106, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush14);
        QBrush brush15(QColor(190, 190, 190, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush15);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush11);
        QBrush brush16(QColor(181, 181, 181, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush16);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        QBrush brush17(QColor(172, 183, 186, 255));
        brush17.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush17);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        groupBox->setPalette(palette1);
        groupBox->setFocusPolicy(Qt::TabFocus);
        layoutWidget = new QWidget(groupBox);
        layoutWidget->setObjectName(QStringLiteral("layoutWidget"));
        layoutWidget->setGeometry(QRect(10, 10, 331, 31));
        horizontalLayout = new QHBoxLayout(layoutWidget);
        horizontalLayout->setSpacing(6);
        horizontalLayout->setContentsMargins(11, 11, 11, 11);
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        label_2 = new QLabel(layoutWidget);
        label_2->setObjectName(QStringLiteral("label_2"));

        horizontalLayout->addWidget(label_2);

        comboBox = new QComboBox(layoutWidget);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush18(QColor(170, 0, 127, 255));
        brush18.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush18);
        QBrush brush19(QColor(255, 0, 191, 255));
        brush19.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush19);
        QBrush brush20(QColor(212, 0, 159, 255));
        brush20.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush20);
        QBrush brush21(QColor(85, 0, 63, 255));
        brush21.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush21);
        QBrush brush22(QColor(113, 0, 84, 255));
        brush22.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush22);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush18);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush23(QColor(212, 127, 191, 255));
        brush23.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush23);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush18);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush19);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush20);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush21);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush22);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush18);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush23);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush21);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush18);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush19);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush20);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush21);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush22);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush21);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush21);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush18);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush18);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush18);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        comboBox->setPalette(palette2);
        comboBox->setAcceptDrops(true);
        comboBox->setAutoFillBackground(true);
        comboBox->setEditable(false);

        horizontalLayout->addWidget(comboBox);

        label_3 = new QLabel(layoutWidget);
        label_3->setObjectName(QStringLiteral("label_3"));

        horizontalLayout->addWidget(label_3, 0, Qt::AlignHCenter);

        comboBox_2 = new QComboBox(layoutWidget);
        comboBox_2->setObjectName(QStringLiteral("comboBox_2"));

        horizontalLayout->addWidget(comboBox_2);

        groupBox_2 = new QGroupBox(centralWidget);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(400, 50, 371, 41));
        widget = new QWidget(groupBox_2);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setGeometry(QRect(0, 10, 361, 31));
        horizontalLayout_2 = new QHBoxLayout(widget);
        horizontalLayout_2->setSpacing(6);
        horizontalLayout_2->setContentsMargins(11, 11, 11, 11);
        horizontalLayout_2->setObjectName(QStringLiteral("horizontalLayout_2"));
        horizontalLayout_2->setContentsMargins(0, 0, 0, 0);
        radioButton_3 = new QRadioButton(widget);
        radioButton_3->setObjectName(QStringLiteral("radioButton_3"));

        horizontalLayout_2->addWidget(radioButton_3);

        radioButton_4 = new QRadioButton(widget);
        radioButton_4->setObjectName(QStringLiteral("radioButton_4"));

        horizontalLayout_2->addWidget(radioButton_4);

        label_4 = new QLabel(widget);
        label_4->setObjectName(QStringLiteral("label_4"));

        horizontalLayout_2->addWidget(label_4);

        spinBox = new QSpinBox(widget);
        spinBox->setObjectName(QStringLiteral("spinBox"));

        horizontalLayout_2->addWidget(spinBox);

        groupBox_3 = new QGroupBox(centralWidget);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(20, 110, 751, 261));
        groupBox_4 = new QGroupBox(groupBox_3);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 20, 341, 231));
        label_5 = new QLabel(groupBox_4);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(30, 20, 31, 16));
        lineEdit = new QLineEdit(groupBox_4);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(70, 20, 191, 16));
        pushButton = new QPushButton(groupBox_4);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(270, 20, 51, 21));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush24(QColor(255, 255, 178, 255));
        brush24.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush24);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush25(QColor(255, 255, 216, 255));
        brush25.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush25);
        QBrush brush26(QColor(127, 127, 89, 255));
        brush26.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush26);
        QBrush brush27(QColor(170, 170, 119, 255));
        brush27.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush27);
        QBrush brush28(QColor(85, 85, 255, 255));
        brush28.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush28);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush7);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush24);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush25);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush24);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush25);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush26);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush27);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush28);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush24);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush25);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush26);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush24);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush25);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush26);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush27);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush26);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush26);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush24);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush24);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush24);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        pushButton->setPalette(palette3);
        pushButton_4 = new QPushButton(groupBox_4);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(270, 40, 51, 21));
        label_8 = new QLabel(groupBox_4);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(30, 40, 31, 16));
        lineEdit_4 = new QLineEdit(groupBox_4);
        lineEdit_4->setObjectName(QStringLiteral("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(70, 40, 191, 16));
        pushButton_5 = new QPushButton(groupBox_4);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(270, 60, 51, 21));
        lineEdit_5 = new QLineEdit(groupBox_4);
        lineEdit_5->setObjectName(QStringLiteral("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(70, 60, 191, 16));
        label_9 = new QLabel(groupBox_4);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(30, 60, 31, 16));
        pushButton_6 = new QPushButton(groupBox_4);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(270, 100, 51, 21));
        pushButton_7 = new QPushButton(groupBox_4);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(270, 120, 51, 21));
        pushButton_8 = new QPushButton(groupBox_4);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(270, 80, 51, 21));
        lineEdit_6 = new QLineEdit(groupBox_4);
        lineEdit_6->setObjectName(QStringLiteral("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(70, 120, 191, 16));
        label_10 = new QLabel(groupBox_4);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(30, 120, 31, 16));
        lineEdit_7 = new QLineEdit(groupBox_4);
        lineEdit_7->setObjectName(QStringLiteral("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(70, 100, 191, 16));
        label_11 = new QLabel(groupBox_4);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(30, 100, 31, 16));
        label_12 = new QLabel(groupBox_4);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(30, 80, 31, 16));
        lineEdit_8 = new QLineEdit(groupBox_4);
        lineEdit_8->setObjectName(QStringLiteral("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(70, 80, 191, 16));
        label_13 = new QLabel(groupBox_4);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(30, 140, 31, 16));
        pushButton_9 = new QPushButton(groupBox_4);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(270, 140, 51, 21));
        lineEdit_9 = new QLineEdit(groupBox_4);
        lineEdit_9->setObjectName(QStringLiteral("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(70, 140, 191, 16));
        lineEdit_17 = new QLineEdit(groupBox_4);
        lineEdit_17->setObjectName(QStringLiteral("lineEdit_17"));
        lineEdit_17->setGeometry(QRect(70, 160, 191, 16));
        label_21 = new QLabel(groupBox_4);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(30, 160, 31, 16));
        pushButton_17 = new QPushButton(groupBox_4);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(270, 160, 51, 21));
        lineEdit_18 = new QLineEdit(groupBox_4);
        lineEdit_18->setObjectName(QStringLiteral("lineEdit_18"));
        lineEdit_18->setGeometry(QRect(70, 180, 191, 16));
        label_22 = new QLabel(groupBox_4);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(30, 180, 31, 16));
        pushButton_18 = new QPushButton(groupBox_4);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(270, 180, 51, 21));
        lineEdit_19 = new QLineEdit(groupBox_4);
        lineEdit_19->setObjectName(QStringLiteral("lineEdit_19"));
        lineEdit_19->setGeometry(QRect(70, 200, 191, 16));
        label_23 = new QLabel(groupBox_4);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(30, 200, 31, 16));
        pushButton_19 = new QPushButton(groupBox_4);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(270, 200, 51, 21));
        label_5->raise();
        lineEdit->raise();
        pushButton->raise();
        pushButton_4->raise();
        label_8->raise();
        lineEdit_4->raise();
        pushButton_5->raise();
        lineEdit_5->raise();
        label_9->raise();
        pushButton_6->raise();
        pushButton_7->raise();
        pushButton_8->raise();
        lineEdit_6->raise();
        label_10->raise();
        lineEdit_7->raise();
        label_11->raise();
        label_12->raise();
        lineEdit_8->raise();
        label_13->raise();
        pushButton_9->raise();
        lineEdit_9->raise();
        lineEdit_17->raise();
        label_21->raise();
        pushButton_17->raise();
        lineEdit_18->raise();
        label_22->raise();
        pushButton_18->raise();
        lineEdit_19->raise();
        label_23->raise();
        pushButton_19->raise();
        groupBox_5 = new QGroupBox(groupBox_3);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(380, 20, 361, 231));
        label_6 = new QLabel(groupBox_5);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(30, 20, 31, 16));
        lineEdit_2 = new QLineEdit(groupBox_5);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(70, 20, 191, 16));
        pushButton_2 = new QPushButton(groupBox_5);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(270, 20, 51, 21));
        pushButton_40 = new QPushButton(groupBox_5);
        pushButton_40->setObjectName(QStringLiteral("pushButton_40"));
        pushButton_40->setGeometry(QRect(270, 40, 51, 21));
        label_44 = new QLabel(groupBox_5);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(30, 40, 31, 16));
        lineEdit_40 = new QLineEdit(groupBox_5);
        lineEdit_40->setObjectName(QStringLiteral("lineEdit_40"));
        lineEdit_40->setGeometry(QRect(70, 40, 191, 16));
        pushButton_41 = new QPushButton(groupBox_5);
        pushButton_41->setObjectName(QStringLiteral("pushButton_41"));
        pushButton_41->setGeometry(QRect(270, 60, 51, 21));
        lineEdit_41 = new QLineEdit(groupBox_5);
        lineEdit_41->setObjectName(QStringLiteral("lineEdit_41"));
        lineEdit_41->setGeometry(QRect(70, 60, 191, 16));
        label_45 = new QLabel(groupBox_5);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(30, 60, 31, 16));
        pushButton_42 = new QPushButton(groupBox_5);
        pushButton_42->setObjectName(QStringLiteral("pushButton_42"));
        pushButton_42->setGeometry(QRect(270, 100, 51, 21));
        pushButton_43 = new QPushButton(groupBox_5);
        pushButton_43->setObjectName(QStringLiteral("pushButton_43"));
        pushButton_43->setGeometry(QRect(270, 120, 51, 21));
        pushButton_44 = new QPushButton(groupBox_5);
        pushButton_44->setObjectName(QStringLiteral("pushButton_44"));
        pushButton_44->setGeometry(QRect(270, 80, 51, 21));
        lineEdit_42 = new QLineEdit(groupBox_5);
        lineEdit_42->setObjectName(QStringLiteral("lineEdit_42"));
        lineEdit_42->setGeometry(QRect(70, 120, 191, 16));
        label_46 = new QLabel(groupBox_5);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(30, 120, 31, 16));
        lineEdit_43 = new QLineEdit(groupBox_5);
        lineEdit_43->setObjectName(QStringLiteral("lineEdit_43"));
        lineEdit_43->setGeometry(QRect(70, 100, 191, 16));
        label_47 = new QLabel(groupBox_5);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(30, 100, 31, 16));
        label_48 = new QLabel(groupBox_5);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(30, 80, 31, 16));
        lineEdit_44 = new QLineEdit(groupBox_5);
        lineEdit_44->setObjectName(QStringLiteral("lineEdit_44"));
        lineEdit_44->setGeometry(QRect(70, 80, 191, 16));
        label_49 = new QLabel(groupBox_5);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(30, 140, 31, 16));
        pushButton_45 = new QPushButton(groupBox_5);
        pushButton_45->setObjectName(QStringLiteral("pushButton_45"));
        pushButton_45->setGeometry(QRect(270, 140, 51, 21));
        lineEdit_45 = new QLineEdit(groupBox_5);
        lineEdit_45->setObjectName(QStringLiteral("lineEdit_45"));
        lineEdit_45->setGeometry(QRect(70, 140, 191, 16));
        lineEdit_46 = new QLineEdit(groupBox_5);
        lineEdit_46->setObjectName(QStringLiteral("lineEdit_46"));
        lineEdit_46->setGeometry(QRect(70, 160, 191, 16));
        label_50 = new QLabel(groupBox_5);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(30, 160, 31, 16));
        pushButton_46 = new QPushButton(groupBox_5);
        pushButton_46->setObjectName(QStringLiteral("pushButton_46"));
        pushButton_46->setGeometry(QRect(270, 160, 51, 21));
        lineEdit_47 = new QLineEdit(groupBox_5);
        lineEdit_47->setObjectName(QStringLiteral("lineEdit_47"));
        lineEdit_47->setGeometry(QRect(70, 180, 191, 16));
        label_51 = new QLabel(groupBox_5);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(30, 180, 31, 16));
        pushButton_47 = new QPushButton(groupBox_5);
        pushButton_47->setObjectName(QStringLiteral("pushButton_47"));
        pushButton_47->setGeometry(QRect(270, 180, 51, 21));
        lineEdit_48 = new QLineEdit(groupBox_5);
        lineEdit_48->setObjectName(QStringLiteral("lineEdit_48"));
        lineEdit_48->setGeometry(QRect(70, 200, 191, 16));
        label_52 = new QLabel(groupBox_5);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(30, 200, 31, 16));
        pushButton_48 = new QPushButton(groupBox_5);
        pushButton_48->setObjectName(QStringLiteral("pushButton_48"));
        pushButton_48->setGeometry(QRect(270, 200, 51, 21));
        label_6->raise();
        lineEdit_2->raise();
        pushButton_2->raise();
        pushButton_40->raise();
        label_44->raise();
        lineEdit_40->raise();
        pushButton_41->raise();
        lineEdit_41->raise();
        label_45->raise();
        pushButton_42->raise();
        pushButton_43->raise();
        pushButton_44->raise();
        lineEdit_42->raise();
        label_46->raise();
        lineEdit_43->raise();
        label_47->raise();
        label_48->raise();
        lineEdit_44->raise();
        label_49->raise();
        pushButton_45->raise();
        lineEdit_45->raise();
        lineEdit_46->raise();
        label_50->raise();
        pushButton_46->raise();
        lineEdit_47->raise();
        label_51->raise();
        pushButton_47->raise();
        lineEdit_48->raise();
        label_52->raise();
        pushButton_48->raise();
        comboBox_2->raise();
        groupBox_4->raise();
        groupBox_5->raise();
        comboBox_2->raise();
        Load = new QPushButton(centralWidget);
        Load->setObjectName(QStringLiteral("Load"));
        Load->setGeometry(QRect(530, 380, 75, 23));
        RunModel = new QPushButton(centralWidget);
        RunModel->setObjectName(QStringLiteral("RunModel"));
        RunModel->setGeometry(QRect(620, 380, 151, 51));
        RunModel->setAutoFillBackground(true);
        RunModel->setAutoDefault(true);
        RunModel->setDefault(true);
        RunModel->setFlat(false);
        Close = new QPushButton(centralWidget);
        Close->setObjectName(QStringLiteral("Close"));
        Close->setGeometry(QRect(530, 410, 75, 23));
        checkBox = new QCheckBox(centralWidget);
        checkBox->setObjectName(QStringLiteral("checkBox"));
        checkBox->setGeometry(QRect(410, 380, 101, 21));
        checkBox_2 = new QCheckBox(centralWidget);
        checkBox_2->setObjectName(QStringLiteral("checkBox_2"));
        checkBox_2->setGeometry(QRect(410, 400, 101, 21));
        pb_logo = new QLabel(centralWidget);
        pb_logo->setObjectName(QStringLiteral("pb_logo"));
        pb_logo->setGeometry(QRect(20, 390, 171, 41));
        pb_logo->setTextFormat(Qt::PlainText);
        pb_logo->setPixmap(QPixmap(QString::fromUtf8(":/images/Resource/pblogo.jpg")));
        Dummy->setCentralWidget(centralWidget);
        groupBox_3->raise();
        radioButton_2->raise();
        radioButton->raise();
        label->raise();
        groupBox->raise();
        groupBox_2->raise();
        Load->raise();
        RunModel->raise();
        Close->raise();
        checkBox->raise();
        checkBox_2->raise();
        widget->raise();
        pb_logo->raise();
        menuBar = new QMenuBar(Dummy);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 849, 21));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        menuEdit = new QMenu(menuBar);
        menuEdit->setObjectName(QStringLiteral("menuEdit"));
        menuAbout = new QMenu(menuBar);
        menuAbout->setObjectName(QStringLiteral("menuAbout"));
        Dummy->setMenuBar(menuBar);
#ifndef QT_NO_SHORTCUT
        label_2->setBuddy(comboBox);
#endif // QT_NO_SHORTCUT

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuEdit->menuAction());
        menuBar->addAction(menuAbout->menuAction());
        menuFile->addAction(actionNew);
        menuFile->addAction(actionOpen_2);
        menuFile->addSeparator();
        menuFile->addAction(actionDelete);
        menuFile->addAction(actionUndo);
        menuAbout->addAction(actionAuthor);
        menuAbout->addAction(actionTool);
        menuAbout->addSeparator();

        retranslateUi(Dummy);
        QObject::connect(Close, SIGNAL(clicked()), Dummy, SLOT(close()));

        QMetaObject::connectSlotsByName(Dummy);
    } // setupUi

    void retranslateUi(QMainWindow *Dummy)
    {
        Dummy->setWindowTitle(QApplication::translate("Dummy", "Cot_n_Pare", 0));
        actionOpen->setText(QApplication::translate("Dummy", "Open", 0));
        actionSave->setText(QApplication::translate("Dummy", "Save", 0));
        actionDelete->setText(QApplication::translate("Dummy", "Delete", 0));
        actionUndo->setText(QApplication::translate("Dummy", "Undo", 0));
        actionAuthor->setText(QApplication::translate("Dummy", "Author", 0));
        actionAuthor->setProperty("Author", QVariant(QString()));
        actionTool->setText(QApplication::translate("Dummy", "Tool", 0));
        actionNew->setText(QApplication::translate("Dummy", "New", 0));
        actionOpen_2->setText(QApplication::translate("Dummy", "Open", 0));
        radioButton->setText(QApplication::translate("Dummy", "Convert to CSV", 0));
        radioButton_2->setText(QApplication::translate("Dummy", "Compare", 0));
        label->setText(QApplication::translate("Dummy", "Step 0: Choose Action", 0));
        groupBox->setTitle(QApplication::translate("Dummy", "Step 1: File Format", 0));
        label_2->setText(QApplication::translate("Dummy", "File Type", 0));
        label_3->setText(QApplication::translate("Dummy", "File Format", 0));
        groupBox_2->setTitle(QApplication::translate("Dummy", "Step 2: Compare Type", 0));
        radioButton_3->setText(QApplication::translate("Dummy", "Same File Type", 0));
        radioButton_4->setText(QApplication::translate("Dummy", "Different Types", 0));
        label_4->setText(QApplication::translate("Dummy", "      # of Files", 0));
        groupBox_3->setTitle(QApplication::translate("Dummy", "Step 3: Specify Files", 0));
        groupBox_4->setTitle(QApplication::translate("Dummy", "Set A: Base", 0));
        label_5->setText(QApplication::translate("Dummy", "File1:", 0));
        pushButton->setText(QApplication::translate("Dummy", "Browse", 0));
        pushButton_4->setText(QApplication::translate("Dummy", "Browse", 0));
        label_8->setText(QApplication::translate("Dummy", "File2:", 0));
        pushButton_5->setText(QApplication::translate("Dummy", "Browse", 0));
        label_9->setText(QApplication::translate("Dummy", "File3:", 0));
        pushButton_6->setText(QApplication::translate("Dummy", "Browse", 0));
        pushButton_7->setText(QApplication::translate("Dummy", "Browse", 0));
        pushButton_8->setText(QApplication::translate("Dummy", "Browse", 0));
        label_10->setText(QApplication::translate("Dummy", "File6:", 0));
        label_11->setText(QApplication::translate("Dummy", "File5:", 0));
        label_12->setText(QApplication::translate("Dummy", "File4:", 0));
        label_13->setText(QApplication::translate("Dummy", "File7:", 0));
        pushButton_9->setText(QApplication::translate("Dummy", "Browse", 0));
        label_21->setText(QApplication::translate("Dummy", "File8:", 0));
        pushButton_17->setText(QApplication::translate("Dummy", "Browse", 0));
        label_22->setText(QApplication::translate("Dummy", "File9:", 0));
        pushButton_18->setText(QApplication::translate("Dummy", "Browse", 0));
        label_23->setText(QApplication::translate("Dummy", "File10:", 0));
        pushButton_19->setText(QApplication::translate("Dummy", "Browse", 0));
        groupBox_5->setTitle(QApplication::translate("Dummy", "Set B: Compare", 0));
        label_6->setText(QApplication::translate("Dummy", "File1:", 0));
        pushButton_2->setText(QApplication::translate("Dummy", "Browse", 0));
        pushButton_40->setText(QApplication::translate("Dummy", "Browse", 0));
        label_44->setText(QApplication::translate("Dummy", "File2:", 0));
        pushButton_41->setText(QApplication::translate("Dummy", "Browse", 0));
        label_45->setText(QApplication::translate("Dummy", "File3:", 0));
        pushButton_42->setText(QApplication::translate("Dummy", "Browse", 0));
        pushButton_43->setText(QApplication::translate("Dummy", "Browse", 0));
        pushButton_44->setText(QApplication::translate("Dummy", "Browse", 0));
        label_46->setText(QApplication::translate("Dummy", "File6:", 0));
        label_47->setText(QApplication::translate("Dummy", "File5:", 0));
        label_48->setText(QApplication::translate("Dummy", "File4:", 0));
        label_49->setText(QApplication::translate("Dummy", "File7:", 0));
        pushButton_45->setText(QApplication::translate("Dummy", "Browse", 0));
        label_50->setText(QApplication::translate("Dummy", "File8:", 0));
        pushButton_46->setText(QApplication::translate("Dummy", "Browse", 0));
        label_51->setText(QApplication::translate("Dummy", "File9:", 0));
        pushButton_47->setText(QApplication::translate("Dummy", "Browse", 0));
        label_52->setText(QApplication::translate("Dummy", "File10:", 0));
        pushButton_48->setText(QApplication::translate("Dummy", "Browse", 0));
        Load->setText(QApplication::translate("Dummy", "LOAD", 0));
        RunModel->setText(QApplication::translate("Dummy", "RUN MODEL", 0));
        Close->setText(QApplication::translate("Dummy", "CLOSE", 0));
        checkBox->setText(QApplication::translate("Dummy", "Save Settings", 0));
        checkBox_2->setText(QApplication::translate("Dummy", "Convert to CSV", 0));
        pb_logo->setText(QString());
        menuFile->setTitle(QApplication::translate("Dummy", "File", 0));
        menuEdit->setTitle(QApplication::translate("Dummy", "Edit", 0));
        menuAbout->setTitle(QApplication::translate("Dummy", "About", 0));
    } // retranslateUi

};

namespace Ui {
    class Dummy: public Ui_Dummy {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DUMMY_H
