######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 1 16:06:55 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += widgets
# Input
SOURCES += hello.cpp
